export const possibleInterests = [{name: 'Cricket', checked: false},
    {name: 'Football', checked: false}, {name: 'Fitness', checked: false},
    {name: 'Environmentalism', checked: false}, {name: 'Leftism', checked: false},
    {name: 'Conservativism', checked: false}, {name: 'Feminism', checked: false},
    {name: 'Urdu Poetry', checked: false}, {name: 'Documentaries', checked: false},
    {name: 'Comedy Shows', checked: false}, {name: 'English Poetry', checked: false},
    {name: 'Hip-Hop', checked: false}, {name: 'Rock', checked: false},
    {name: 'Pop Music', checked: false}, {name: 'South Asian Classical Music', checked: false},
    {name: 'Western Classical Music', checked: false}, {name: 'Experimental Music', checked: false},
    {name: 'Non-Fiction Books', checked: false}, {name: 'Dramas', checked: false},
    {name: 'K-Pop', checked: false}, {name: 'K-Dramas', checked: false},
    {name: 'Pakistani Television', checked: false}, {name: 'Making Music', checked: false},
    {name: 'Theatre', checked: false}, {name: 'Filmmaking', checked: false},
    {name: 'Action Flicks', checked: false}, {name: 'Comedy Flicks', checked: false},
    {name: 'Sci-Fi', checked: false}, {name: 'TV shows', checked: false},
    {name: 'RnB Music', checked: false}, {name: 'Electronic Music', checked: false},
    {name: 'South Asian Films', checked: false}, {name: 'Traveling', checked: false},
    {name: 'Foodie', checked: false}, {name: 'Crypto', checked: false},
    {name: 'Memes', checked: false}, {name: 'Chess', checked: false},
    {name: 'Video Games', checked: false}, {name: 'Painting', checked: false},
    {name: 'Fantasy Books', checked: false}, {name: 'Writing Poetry', checked: false},
    {name: 'Writing Articles', checked: false}, {name: 'Art House Cinema', checked: false},
    {name: 'Comic Books', checked: false}, {name: 'Comic Book Movies', checked: false},
    {name: 'South Asian Music', checked: false}, {name: 'Horror Films', checked: false},
    {name: 'Horror Books', checked: false}, {name: 'Romantic Films', checked: false},
    {name: 'Romantic Books', checked: false},
    {name: 'Cooking', checked: false}, {name: 'History', checked: false},
    {name: 'True Crime Books', checked: false}, {name: 'True Crime TV', checked: false},
    {name: 'Metal', checked: false}, {name: 'Digital Art', checked: false},
    {name: 'Sketching', checked: false}, {name: 'DIY', checked: false},
    {name: 'Singing', checked: false}, {name: 'Fashion', checked: false},
    {name: 'Board Games', checked: false}, {name: 'Tech', checked: false}];